kendaraan = ["B 1234 abc", "beat", "125cc", "hitam"]
kendaraan.append("Rp 15.000.000")
kendaraan.append("roda dua")

kendaraan.insert(2, "honda")
kendaraan.insert(3, "motor matic")
# print(kendaraan)
kodekendaraan = (kendaraan[0])
print("Kode Kendaraan :", kodekendaraan)
namakendaraan = (kendaraan[1])
print("Nama Kendaraan :", namakendaraan)
merkkendaraan = (kendaraan[2])
print("Merk Kendaraan :", merkkendaraan)
jeniskendaraan = (kendaraan[3])
print("Jenis Kendaraan :", jeniskendaraan)
cckendaraan = (kendaraan[4])
print("CC Kendaraan :", cckendaraan)
warnakendaraan = (kendaraan[5])
print("Warna Kendaraan :", warnakendaraan)
hargakendaraan = (kendaraan[6])
print("Harga Kendaraan :", hargakendaraan)
jumlahban = (kendaraan[7])
print("Jumlah Ban :", jumlahban)
